### ISSUE TITLE
Bytes parser performance

### ISSUE THREAD

**Issue by rukai** [aembke/redis-protocol.rs#20]
This isnt really an issue for redis-protocol, but raising an issue here seemed like the easiest way to make a discussion on this topic.

I was experimenting with writing a parser for cql (cassandra sql) using nom and https://github.com/aembke/redis-protocol.rs/blob/main/src/nom_bytes.rs
The experiment is available here https://github.com/rukai/cqlparser

I did the following:
1. Implemented the nom parser the simple way, just pass around an `&[u8]` and output an ast that allocates Strings everywhere.
2. Write benchmarks for this.
3. Ported my parser to use nom_bytes + Bytes.
4. Ran the benchmarks for both the old and new implementation and noticed significant performance regressions.

```
git clone https://github.com/rukai/cqlparser
git checkout main
cargo bench
git checkout convert_to_bytes
cargo bench
```
![image](https://user-images.githubusercontent.com/5120858/153985845-0dd2cbe8-2cc2-4a6c-b39d-57310979d917.png)

I can kind of see why this would occur, a Bytes would be more expensive to clone around than an `&[u8]` and nom does a lot of cloning going through all the combinators.
Also maybe the logic in the Bytes Clone is preventing optimizations that normally keep nom performant?

Did you benchmark a Bytes and non-Bytes equivalent parser before settling on a Bytes parser?
Might be worth investigating that if you havent already.

If you did observe performance issues when combining nom and Bytes and found workarounds I would be interested in hearing them.
I noticed that redis-protocol tends to manually implement some stuff that nom does for you, is that related to this problem?

**Comment by aembke** [comment]
Hi @rukai,

Yeah this is something I noticed too. In fact, the `decode_mut` parser function you're using in shotover (and the same one I use in fred) doesn't use `Bytes` at all with the nom interface. 

The "main" `decode_mut` parser function, which is the one I'm interested in using and supporting down the road (with `BytesMut` as the input) does the following: 

1. Immediately call `as_bytes()` on the `BytesMut` to get a slice view into the buffer.
2. Call the nom functions with inputs of `(&[u8], usize)` where the second value tracks the parsing offset into the slice.
3. Create [fake frame structs](https://github.com/aembke/redis-protocol.rs/blob/main/src/decode_mut/frame.rs#L23) which just hold the `usize` offsets `(start, end)` into the buffer when they detect a frame.
4. At the very end once the final ending offset into the original `BytesMut` is known, perform one `split` and `freeze` on the `BytesMut`.
5. Do a depth-first traversal of the nested "fake" frames + the now frozen `Bytes` to convert to the "real" frames.

This approach was a lot more work to implement ([I had to write the parser twice essentially](https://github.com/aembke/redis-protocol.rs/blob/main/src/decode_mut/resp3.rs#L419-L427), but I probably could have abstracted it better with the nom traits), but I think it strikes a good balance. It allows for zero-copy parsing and doesn't require using `Bytes` with `nom`, therefore avoiding the added overhead of the `Bytes` clone like you pointed out. 

When I originally wrote 4.x I did the `NomBytes` interface first, then implemented the `decode_mut` feature interfaces. I've been thinking more about this and I might either get rid of the non `decode_mut` interfaces for both the performance reasons you mentioned, and the fact that I don't think anybody really needs that. From what I've seen it's pretty ubiquitous to have `BytesMut` as your input to the parsing logic, but I could be wrong there. At a minimum I'll probably swap out the underlying implementation in the `Bytes` parsing logic to use `&[u8]` under the hood. Either way I'm not sure if anybody uses that (you and I both use the `decode_mut` interface at least), so we'll see. 

At the moment though I really need to focus on `fred` so this is all stuff I likely wont get to for a few months.

**Comment by rukai** [comment]
Thanks for the in depth response!
It sounds like such an approach would be even trickier for parsing CQL (a text language instead of a binary protocol)
So I'm going to stick with allocating `String`s for now but will definitely investigate your approach or something similar if parsing shows up when profiling.
